# Generated by Django 3.2.16 on 2024-01-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='is_public',
        ),
        migrations.AddField(
            model_name='letter',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='letter',
            name='author',
            field=models.CharField(max_length=255),
        ),
    ]
