# Generated by Django 3.2.16 on 2024-01-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_rename_receiver_gallery_receiver_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='receiver_id',
            new_name='receiver',
        ),
    ]
