# Generated by Django 3.2.16 on 2024-01-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images/'),
        ),
    ]
