# Generated by Django 3.2.16 on 2024-01-16 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0004_alter_person_picture_url'),
        ('epistle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='receiver',
            field=models.ForeignKey(default=41, on_delete=django.db.models.deletion.CASCADE, related_name='received_letters', to='peoples.person'),
            preserve_default=False,
        ),
    ]
